/**
 * Every word on the site (English). The Arabic twin in ./ar.ts has exactly
 * this shape — TypeScript fails the build if a key is missing there.
 *
 * Company facts (offices, clients, team, stats) stay in `src/lib/site.ts`;
 * case studies in `src/data/portfolio.ts`; open roles in `src/data/careers.ts`.
 * Headline arrays are one entry per line: display type is set line by line.
 */

export const en = {
  meta: {
    siteTitle: "Forward-thinking creative partner",
    description:
      "PSdigital is a forward-thinking creative partner for MENA and beyond. Strategy, creativity and innovation that build brands and digital products that grow.",
    keywords: ["creative agency", "digital agency", "branding", "social media", "website design", "app design", "performance marketing", "MENA", "Egypt", "Dubai"],
    pages: {
      about: { title: "About", description: "Who we are: 80+ strategists, designers, engineers and producers in Alexandria and Dubai, working as one creative partner." },
      services: { title: "Services", description: "Social media, branding, website & app design, creative production, digital consultation and performance marketing — delivered in-house." },
      work: { title: "Work", description: "Selected work for Texas Chicken, Shark Tank Egypt, Sinclair, Physiowell and more — brands, platforms and campaigns across MENA." },
      team: { title: "Team", description: "The people behind the work at PSdigital — leadership, discipline leads and the studio in Alexandria and Dubai." },
      careers: { title: "Careers", description: "Open roles at PSdigital. Apply in three steps and send us your work." },
      contact: { title: "Contact", description: "Talk to PSdigital. Write to us, find the studios, or start a project — we reply within two working days." },
      industries: { title: "Industries", description: "Restaurants, healthcare, media, real estate and lifestyle brands — the sectors we know, each backed by real case studies." },
      insights: { title: "Insights", description: "Practical notes from building and marketing brands and digital products across MENA." },
      start: { title: "Start a project", description: "Tell us about your project in five short steps. A strategist and a creative lead reply within two working days." },
      notFound: { title: "Page not found", description: "This page does not exist." },
    },
  },

  nav: {
    /** Sitemap order. Services and Industries open a menu of their pages. */
    primary: [
      { label: "About", href: "/about" },
      { label: "Work", href: "/work" },
      { label: "Services", href: "/services" },
      { label: "Industries", href: "/industries" },
      { label: "Insights", href: "/insights" },
      { label: "Careers", href: "/careers" },
    ],
    contact: { label: "Contact", href: "/contact" },
    start: { label: "Start a project", href: "/start" },
    team: { label: "Team", href: "/team" },
    menus: { services: "All services", industries: "All industries", flagship: "Flagship" },
  },

  ui: {
    skip: "Skip to content",
    home: "Home",
    homeLabel: "PSdigital — home",
    mainNav: "Main",
    menu: "Menu",
    close: "Close",
    language: "Language",
    switchTo: "العربية",
    scroll: "Scroll",
    view: "View",
    viewCase: "View case",
    all: "All",
    next: "Next",
    previous: "Previous",
    back: "Back",
    readMore: "Read more",
    localTime: "Local time",
    backToTop: "Back to top",
    directions: "Get directions",
    copyright: "All rights reserved.",
    loading: "Loading",
    required: "Required",
    optional: "Optional",
  },

  footer: {
    closing: ["Endless", "possibilities"],
    lead: "Have something in mind? We would like to hear it.",
    sitemap: "Sitemap",
    services: "Services",
    industries: "Industries",
    company: "Company",
    studios: "Studios",
    write: "Write to us",
    careers: "Join the team",
  },

  home: {
    hero: {
      eyebrow: "Creative & digital partner",
      title: ["Endless", "possibilities"],
      intro: "Strategy, creativity and innovation, working as one. We build brands and digital products that drive growth, across MENA and beyond.",
      primary: "See the work",
      secondary: "What we do",
      location: "Alexandria — Dubai",
      nowShowing: "Now showing",
    },
    numbers: {
      label: "Results we can show",
      title: ["Numbers from", "real projects"],
      intro: "Every figure below comes from work we delivered and measured with the client.",
      items: [
        { value: "16×", caption: "return on ad spend", client: "ZEE" },
        { value: "10M", caption: "people reached every month", client: "Pharco" },
        { value: "50", caption: "days to design and build a site for 5 countries", client: "Burger King" },
        { value: "1 → 15", caption: "branches since we started working together", client: "Beit El Gomla" },
      ],
    },
    testimonials: {
      label: "In our clients' words",
      pending: "Quote to collect",
      items: [
        { quote: "Your client's words go here: one sentence on what changed after launch.", name: "Name", role: "Title, Company", pending: true },
        { quote: "A second client's words: the result they would tell a peer about.", name: "Name", role: "Title, Company", pending: true },
      ],
    },
    positioning: {
      label: "Who we are",
      statement:
        "PSdigital is a forward-thinking creative partner. We bring strategy, creativity and innovation into one room, so the idea that wins the brief is the idea that ships, and it keeps moving your numbers long after launch.",
      pillars: [
        { title: "Strategy", body: "A point of view before a plan." },
        { title: "Creativity", body: "Work people stop for, and remember." },
        { title: "Innovation", body: "Platforms built to grow with you." },
      ],
    },
    work: {
      label: "Projects",
      title: ["Selected", "work"],
      intro: "Brand systems, platforms and campaigns for companies that run across markets. Every case is designed, built and measured in-house.",
      cta: "All work",
    },
    services: {
      label: "What we do",
      title: ["Six", "disciplines"],
      intro: "One team, no hand-offs. Pick the one you need, or let them work together.",
      cta: "All services",
    },
    industries: {
      label: "Industries",
      title: ["We know", "your sector"],
      intro: "Restaurants are where we are strongest. We also build and market for healthcare, media, real estate and lifestyle brands.",
      cta: "All industries",
    },
    clients: {
      label: "Clients",
      title: ["Brands", "we move"],
      intro: "From global names to fast-growing regional challengers.",
    },
    process: {
      label: "How we work",
      title: ["Our", "process"],
    },
    insights: {
      label: "Insights",
      title: ["What we", "have learned"],
      intro: "Practical notes from the brands and platforms we build and run.",
      cta: "All insights",
    },
    closing: {
      label: "Next",
      title: ["Let's build", "your brand", "together"],
      body: "Tell us where you want to go. A strategist and a creative lead will reply within two working days.",
      primary: "Start a project",
      secondary: "Join the team",
    },
  },

  services: {
    hero: {
      label: "Services",
      title: ["Every", "discipline,", "one team"],
      intro:
        "Six disciplines delivered end to end by 80+ in-house specialists. Strategy shapes the identity, and the identity shapes the platform, the campaign and every post that runs on it.",
    },
    labels: { deliverables: "What you get", proof: "See it at work", index: "Discipline", explore: "Explore" },
    detail: {
      back: "All services",
      deliverables: { label: "What you get", title: ["What we", "deliver"] },
      work: { label: "Selected work", title: ["In", "practice"], all: "All {service} work" },
      industries: { label: "Industries", title: ["Where it", "works"] },
      faq: { label: "Questions", title: ["Frequently", "asked"] },
      closing: {
        label: "Next",
        title: ["Start with", "one discipline"],
        body: "Most partners start with one discipline and grow into several. Tell us where you are starting.",
        primary: "Start a project",
        secondary: "All services",
      },
    },
    list: [
      {
        slug: "social-media",
        title: "Social Media",
        headline: ["Always", "on"],
        summary: "Strategy, content and community for brands that publish every day, in Arabic and English.",
        intro: "Strategy, content and community for brands that publish every day. One team plans the calendar, makes the posts and answers the comments, in Arabic and English.",
        faq: [
          { question: "Do you work in Arabic and English?", answer: "Yes. We plan, write and manage content in both, including mixed tones where the brand calls for it." },
          { question: "Can you start a brand's accounts from zero?", answer: "Yes. Shark Tank Egypt started with no social presence; we built the accounts and grew them season after season." },
          { question: "How do you report?", answer: "Monthly, against the goals we agreed at the start: reach where it matters, but also leads, applications or sales." },
        ],
        deliverables: ["Channel strategy", "Content calendars", "Always-on creative", "Community management", "Influencer programmes", "Social listening & reporting"],
        proof: "shark-tank-egypt",
        image: "/images/projects/yumochi/hero.webp",
      },
      {
        slug: "branding",
        title: "Branding",
        headline: ["Built", "to last"],
        summary: "Positioning, identity and bilingual brand systems that travel across markets without losing their voice.",
        intro: "Positioning, identity and bilingual brand systems built to travel. We design in Arabic and English from the first sketch, so the brand reads the same in every market.",
        faq: [
          { question: "Can one brand work across many markets?", answer: "Yes. Texas Chicken runs one bilingual brand system across sixteen markets in the Middle East and Africa." },
          { question: "Do you design in Arabic from the start?", answer: "Always. Arabic and English are designed together, never translated after the fact." },
          { question: "What do we get at the end?", answer: "Guidelines and toolkits your team and partners can use without us in the room." },
        ],
        deliverables: ["Brand strategy & positioning", "Naming & verbal identity", "Visual identity systems", "Bilingual typography", "Guidelines & toolkits", "Packaging & retail"],
        proof: "texas-chicken",
        image: "/images/projects/texas-chicken/hero.webp",
      },
      {
        slug: "website-app-design",
        title: "Website & App Design",
        headline: ["Designed", "& built"],
        summary: "Websites, ordering apps, loyalty and kiosks: researched, designed and engineered under one roof.",
        intro: "Websites, ordering apps, loyalty and kiosks: researched, designed and engineered under one roof, so what is designed is what ships.",
        faq: [
          { question: "Can one platform serve several countries?", answer: "Yes. The Texas Chicken ordering app replaced sixteen country-by-country experiences with one market-aware journey." },
          { question: "Do you build as well as design?", answer: "Yes. Research, UI and engineering sit in the same team, from the first flow to the release." },
          { question: "Do you support the product after launch?", answer: "Yes. We keep improving and supporting products once they are live." },
        ],
        deliverables: ["UX research & flows", "UI design systems", "Websites & e-commerce", "iOS & Android apps", "Loyalty & ordering", "Headless & custom builds"],
        proof: "million-pound-menu",
        image: "/images/projects/shark-tank-egypt/web-desktop.webp",
      },
      {
        slug: "creative-production",
        title: "Creative Production",
        headline: ["Made", "in-house"],
        summary: "Photography, film, motion and 3D produced by our own studio, from key visual to always-on assets.",
        intro: "Photography, film, motion and 3D produced by our own studio. The key visual and the hundredth always-on post come from the same team.",
        faq: [
          { question: "Do you shoot in-house?", answer: "Yes. Art direction, photography, film and post-production are handled by our own studio." },
          { question: "Can you produce for social and out-of-home?", answer: "Yes. M Squared's “Beyond Time.” ran from billboards to street posters to the feed." },
          { question: "How fast can you turn content around?", answer: "For formats on air, the same week. Shark Tank Egypt's content goes live with each episode." },
        ],
        deliverables: ["Art direction", "Photography", "Film & TVC", "Motion & 3D", "Post-production", "Studio & location shoots"],
        proof: "m-squared",
        image: "/images/projects/m-squared/hero.webp",
      },
      {
        slug: "digital-consultation",
        title: "Digital Consultation",
        headline: ["Think", "first"],
        summary: "Audits, roadmaps and a clear point of view before anything is designed or bought.",
        intro: "Audits, roadmaps and a clear point of view before anything is designed or bought. We look at where you are, decide where to go, and plan the route.",
        faq: [
          { question: "What does a consultation produce?", answer: "A written audit, a prioritised roadmap and the budget it needs, ready for your team or ours." },
          { question: "Can you work with our in-house team?", answer: "Yes. Many engagements end with your team running the plan, with us on call." },
          { question: "Why not start with the campaign?", answer: "Gaps found in a plan cost far less to fix than gaps found after the spend." },
        ],
        deliverables: ["Digital & brand audits", "Audience & market research", "Channel & platform roadmaps", "Marketing technology", "Team & process design", "Workshops"],
        proof: "sinclair-aesthetics",
        image: "/images/projects/sinclair-aesthetics/showcase.webp",
      },
      {
        slug: "performance-marketing",
        title: "Performance Marketing",
        headline: ["Measured,", "not guessed"],
        summary: "Paid media, SEO and continuous testing, measured against revenue rather than impressions.",
        intro: "Paid media, SEO and continuous testing, measured against revenue rather than impressions. Every creative is a test, and the winners get the budget.",
        faq: [
          { question: "How do you measure success?", answer: "By the outcome you care about: leads, bookings, orders or return on ad spend. For Physiowell that meant up to 10x ROAS." },
          { question: "Which platforms do you run?", answer: "Meta, TikTok, Snapchat, X and Google, plus SEO and content for search." },
          { question: "How quickly will we see results?", answer: "Tests start returning signal within weeks; we scale what works and stop what does not." },
        ],
        deliverables: ["Media planning & buying", "Performance creative", "SEO & content", "Tracking & attribution", "A/B testing", "Reporting & optimisation"],
        proof: "physiowell",
        image: "/images/projects/physiowell/mood.webp",
      },
    ],
    process: { label: "How we work", title: ["From first idea", "to last pixel"] },
    closing: {
      label: "More than one discipline?",
      title: ["Let's build", "the whole", "system"],
      body: "Most of our partners start with one discipline and grow into several. Tell us where you are starting.",
      primary: "Start a project",
      secondary: "See the work",
    },
  },

  work: {
    hero: {
      label: "Work",
      title: ["Selected", "work"],
      intro: "Brand systems, platforms and campaigns for companies that run across markets. Filter by what you need.",
    },
    filterLabel: "Filter work by discipline",
    industryFilterLabel: "Filter work by industry",
    filters: { label: "Filter", service: "Service", industry: "Industry", clear: "Clear filters", results: "projects" },
    empty: "No work in this discipline yet.",
    clients: { label: "Clients", title: ["Trusted", "by"] },
    case: {
      client: "Client",
      market: "Market",
      industry: "Industry",
      services: "Disciplines",
      deliverables: "Deliverables",
      next: "Next case",
      back: "All work",
      overview: "Overview",
      challenge: "The challenge",
      approach: "What we did",
      results: "The result",
      review: "Client review",
      links: "See it live",
      linkNames: {
        website: "Website",
        app: "App",
        instagram: "Instagram",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        tiktok: "TikTok",
        youtube: "YouTube",
        x: "X",
        behance: "Behance",
      },
    },
  },

  industries: {
    hero: {
      label: "Industries",
      title: ["Built for", "your sector"],
      intro: "Every industry below links to real work. Restaurants are our deepest specialism; the others are sectors where we have shipped and measured.",
    },
    labels: {
      projects: "{count} projects",
      back: "All industries",
      challenges: { label: "What we hear", title: ["The problems", "we solve"] },
      helps: { label: "How we help", title: ["What we build", "and run"] },
      work: { label: "Our work", title: ["In this", "sector"] },
    },
    closing: {
      label: "Your sector",
      title: ["Tell us", "what you sell"],
      body: "Whatever the market, the first conversation is about your customers. Tell us who they are.",
      primary: "Start a project",
      secondary: "See the work",
    },
  },

  insights: {
    hero: {
      label: "Insights",
      title: ["What we", "have learned"],
      intro: "Practical notes from building and marketing brands and digital products in the region, written from the work.",
    },
    filterLabel: "Filter insights by topic",
    minutes: "{count} min read",
    toc: "In this article",
    related: "Read the case study",
    back: "All insights",
    more: { label: "Keep reading", title: ["More", "insights"] },
  },

  about: {
    hero: {
      label: "About",
      title: ["Forward", "thinking", "partner"],
      intro:
        "We are a creative and digital partner for brands across MENA and beyond. Strategy, creativity and innovation work as one team in Alexandria and Dubai.",
    },
    statement: {
      label: "Our story",
      text: "We started PSdigital to close the gap between the people who plan a brand and the people who build it. Today more than eighty specialists work as one team: strategy, design, technology and performance in the same room, on the same brief.",
    },
    numbers: {
      label: "In numbers",
      items: [
        { value: 80, suffix: "+", label: "In-house specialists" },
        { value: 6, suffix: "", label: "Disciplines, end to end" },
        { value: 16, suffix: "", label: "Markets on one brand system" },
        { value: 2023, suffix: "", label: "Digital Agency of the Year" },
      ],
    },
    principles: { label: "What we believe", title: ["Why brands", "stay"] },
    process: { label: "How we work", title: ["Our", "process"] },
    offices: { label: "Studios", title: ["Two cities,", "one team"] },
    closing: {
      label: "Work with us",
      title: ["Let's build", "what's next"],
      body: "Bring us the brief, the launch or the problem. We will bring the whole team.",
      primary: "Start a project",
      secondary: "Meet the team",
    },
  },

  team: {
    hero: {
      label: "Team",
      title: ["People", "behind", "the work"],
      intro: "Strategists, designers, engineers, writers and producers under one roof. The people who win the brief are the people who ship it.",
    },
    leadership: {
      label: "Leadership",
      quote:
        "We built PSdigital so the people who win the brief are the same people who ship it. Nothing gets lost when nobody has to hand anything over.",
      portraitAlt: "Portrait of the PSdigital Chief Executive Officer",
    },
    leads: {
      label: "Discipline leads",
      title: ["The people", "who set the bar"],
      intro: "Each discipline has a lead who reviews every piece of work before it leaves the studio.",
      more: { value: "80+", title: "specialists behind them", action: "Join them" },
    },
    disciplines: {
      label: "Crafts",
      title: ["Seven crafts,", "one room"],
      items: [
        { title: "Strategy", body: "Audience, positioning and the point of view behind every brief." },
        { title: "Design", body: "Identity, campaign and product design, bilingual from day one." },
        { title: "Motion", body: "2D, 3D and film that make brands move the way they sound." },
        { title: "Content", body: "Copy, social and production for brands that publish every day." },
        { title: "Development", body: "Websites, ordering platforms and kiosks, engineered in-house." },
        { title: "UI/UX", body: "Research, flows and design systems that scale across markets." },
        { title: "Performance", body: "Paid media and testing measured against real numbers." },
      ],
    },
    closing: {
      label: "Want a seat in the room?",
      title: ["Join", "the team"],
      body: "We hire people who want to see an idea through, from the first sketch to the numbers it moves.",
      primary: "Open roles",
      secondary: "About us",
    },
  },

  careers: {
    hero: {
      label: "Careers",
      title: ["Make", "what's", "next"],
      intro: "Join 80+ strategists, designers, engineers, writers and producers in Alexandria and Dubai. Apply in three steps and let your work speak first.",
      cta: "Apply now",
    },
    values: {
      label: "Life at PSdigital",
      title: ["Good work,", "good rooms"],
      items: [
        { title: "Craft over volume", body: "Fewer projects, done properly, with your name on the work." },
        { title: "Everyone in the room", body: "Every discipline shares the brief, the timeline and the credit." },
        { title: "Measured, not guessed", body: "Ideas are tested against real numbers. That is how we learn." },
        { title: "Growth is the job", body: "Mentorship, reviews and time to learn are part of the week." },
      ],
    },
    role: {
      back: "All roles",
      view: "View role",
      apply: { label: "Apply", title: ["Apply for", "this role"] },
      open: {
        id: "open-application",
        title: "Open application",
        department: "Any team",
        location: "Alexandria or Dubai",
        type: "Full-time",
        summary: "Don't see your role? Tell us what you do best and where you would fit. We read every application, and if there is a fit now or later, we will be in touch.",
        cta: "Send an open application",
        prompt: "Don't see your role?",
      },
    },
    roles: {
      label: "Open roles",
      title: ["Where you", "could fit"],
      filterLabel: "Filter roles by team",
      allTeams: "All teams",
      youWill: "You will",
      youBring: "You bring",
      apply: "Apply for this role",
      empty: "No roles in this team right now. Send an open application below.",
    },
    apply: {
      label: "Apply",
      title: ["Three", "steps"],
      intro: "No cover letter needed. Tell us who you are, show us your work, and send it.",
      steps: ["You", "Your work", "Send"],
      fields: {
        name: { label: "Full name", placeholder: "Your name" },
        email: { label: "Email", placeholder: "you@email.com" },
        phone: { label: "Phone", placeholder: "+20 …" },
        role: { label: "Role", placeholder: "Choose a role" },
        openApplication: "Open application",
        portfolio: { label: "Portfolio or CV link", placeholder: "https://" },
        file: { label: "Or upload a PDF", hint: "PDF, up to 8 MB", choose: "Choose file", replace: "Replace" },
        note: { label: "A few lines about you", placeholder: "The work you are proudest of, and why" },
        consent: "I agree that PSdigital may keep my application for 12 months to contact me about roles.",
      },
      review: "Review",
      continue: "Continue",
      back: "Back",
      submit: "Send application",
      sending: "Sending…",
      success: {
        title: "Application received.",
        body: "Thank you. The lead of your discipline reviews every application and we reply to everyone, usually within ten working days.",
        again: "Send another",
      },
      fallback: {
        title: "One last step",
        body: "Online applications are not connected yet. Your email app will open with everything filled in. Attach your PDF there.",
        action: "Open email",
      },
      errors: {
        name: "Please tell us your name.",
        email: "Please enter a valid email address.",
        work: "Add a portfolio link or upload a PDF.",
        url: "Please enter a full link, starting with https://",
        file: "Please upload a PDF up to 8 MB.",
        consent: "Please confirm so we can keep your application.",
        server: "Something went wrong on our side. Please try again, or write to us directly.",
      },
      email: { subject: "Application — {role}", role: "Role", name: "Name", email: "Email", phone: "Phone", portfolio: "Portfolio", note: "About me" },
    },
    process: {
      label: "How we hire",
      title: ["Four steps,", "no surprises"],
      steps: [
        { title: "Apply", body: "Send your work and a few lines. We reply to everyone." },
        { title: "Meet", body: "A conversation with the lead of your discipline." },
        { title: "Work together", body: "A short, paid exercise on a real brief." },
        { title: "Offer", body: "A clear offer, usually within two weeks." },
      ],
    },
  },

  contact: {
    hero: {
      label: "Contact",
      title: ["Let's", "talk"],
      intro: "Tell us about the brand, the launch or the problem. A strategist and a creative lead read every enquiry and reply within two working days.",
    },
    form: {
      label: "Start a project",
      fields: {
        name: { label: "Your name", placeholder: "Full name" },
        email: { label: "Email", placeholder: "you@company.com" },
        company: { label: "Company", placeholder: "Brand or organisation" },
        message: { label: "The project", placeholder: "What are you trying to achieve, and by when?" },
      },
      interests: "I'm interested in",
      budget: { label: "Budget range", options: ["Under $10k", "$10k – $25k", "$25k – $50k", "$50k – $100k", "$100k+"] },
      submit: "Send enquiry",
      sending: "Sending…",
      privacy: "We only use your details to reply to this enquiry.",
      success: { title: "Thank you — it's with us.", body: "A strategist and a creative lead will reply within two working days.", again: "Send another" },
      fallback: {
        title: "One last step",
        body: "Online enquiries are not connected yet. Your email app will open with everything filled in.",
        action: "Open email",
      },
      errors: {
        name: "Please tell us your name.",
        email: "Please enter a valid email address.",
        message: "Tell us a little about the project.",
        server: "Something went wrong on our side. Please try again, or write to us directly.",
      },
      email: { subject: "Project enquiry — {company}", name: "Name", email: "Email", company: "Company", interests: "Interested in", budget: "Budget", message: "The project" },
    },
    direct: { label: "Direct", email: "New business", careers: "Careers" },
    brief: { label: "Planning a project?", body: "A full brief gets you a faster, more useful first call.", action: "Start a project" },
    next: {
      label: "What happens next",
      steps: [
        { title: "We read it", body: "A strategist and a creative lead review your brief within two working days." },
        { title: "We talk", body: "A 30-minute call about goals, markets and timing." },
        { title: "We propose", body: "A scoped plan with team, timeline and investment, usually within a week." },
      ],
    },
    offices: { label: "Studios" },
  },

  start: {
    hero: {
      label: "Start a project",
      title: ["Tell us", "about it"],
      intro: "Five short steps, about two minutes. The more we know up front, the more useful our first conversation will be.",
    },
    label: "Project brief",
    steps: ["What you need", "The project", "Budget & timing", "Your details", "Review"],
    needs: { title: "What do you need?", hint: "Choose everything that applies.", unsure: "Not sure yet" },
    project: {
      title: "About the project",
      industry: { label: "Industry", placeholder: "Choose one", other: "Other" },
      markets: { label: "Markets", options: ["Egypt", "UAE", "Saudi Arabia", "Bahrain", "Kuwait", "Qatar", "Oman", "Other"] },
      description: {
        label: "Describe the project",
        placeholder: "For example: an ordering app for our restaurants in Egypt and the UAE, with loyalty and a kiosk in our biggest branches.",
        hint: "At least 20 characters.",
      },
    },
    budget: {
      title: "Budget and timing",
      budget: { label: "Budget", options: ["Under $10k", "$10k – $25k", "$25k – $50k", "$50k – $100k", "$100k+", "Not sure yet"] },
      timing: { label: "Timing", options: ["As soon as possible", "Within 1–3 months", "Within 3–6 months", "Flexible"] },
    },
    details: {
      title: "Your details",
      name: { label: "Full name", placeholder: "Your name" },
      company: { label: "Company", placeholder: "Brand or organisation" },
      email: { label: "Work email", placeholder: "you@company.com" },
      phone: { label: "Phone", placeholder: "+20 …" },
      role: { label: "Your role", placeholder: "e.g. Marketing director" },
    },
    review: { title: "Review and send", empty: "Not given" },
    continue: "Continue",
    back: "Back",
    toReview: "Review",
    submit: "Send brief",
    sending: "Sending…",
    privacy: "We only use your details to reply to this brief.",
    errors: {
      needs: "Choose at least one option, or “Not sure yet”.",
      description: "Add a few more words about the project (at least 20 characters).",
      budget: "Choose a budget range and a timing.",
      name: "Please tell us your name.",
      email: "Please enter a valid email address.",
      server: "Something went wrong on our side. Please try again, or write to us directly.",
    },
    success: { title: "Thank you — your brief is with us.", body: "A strategist and a creative lead will reply within two working days." },
    fallback: { title: "One last step", body: "Online briefs are not connected yet. Your email app will open with every answer filled in.", action: "Open email" },
    email: {
      subject: "Project brief — {company}",
      needs: "Needs",
      industry: "Industry",
      markets: "Markets",
      description: "The project",
      budget: "Budget",
      timing: "Timing",
      name: "Name",
      company: "Company",
      email: "Email",
      phone: "Phone",
      role: "Role",
    },
    next: {
      label: "What happens next",
      steps: [
        { title: "We read it", body: "Your brief reaches a strategist and a creative lead within one working day." },
        { title: "We talk", body: "A 30-minute call about goals, markets and timing." },
        { title: "We propose", body: "A scoped plan with team, timeline and investment, usually within a week." },
      ],
    },
  },

  notFound: {
    label: "404",
    title: ["Lost in", "the glass"],
    body: "The page you are looking for has moved or never existed.",
    action: "Back home",
  },
} as const;

export type SiteCopyEn = typeof en;
