/**
 * Every word on the site (English). The Arabic twin in ./ar.ts has exactly
 * this shape — TypeScript fails the build if a key is missing there.
 *
 * Company facts (offices, clients, team, stats) stay in `src/lib/site.ts`;
 * case studies in `src/data/portfolio.ts`; open roles in `src/data/careers.ts`.
 * Headline arrays are one entry per line: display type is set line by line.
 */

export const en = {
  meta: {
    siteTitle: "Forward-thinking creative partner",
    description:
      "PSdigital is a forward-thinking creative partner for MENA and beyond. Strategy, creativity and innovation that build brands and digital products that grow.",
    keywords: ["creative agency", "digital agency", "branding", "social media", "website design", "app design", "performance marketing", "MENA", "Egypt", "Dubai"],
    pages: {
      about: { title: "About", description: "Who we are: 80+ strategists, designers, engineers and producers in Alexandria and Dubai, working as one creative partner." },
      services: { title: "Services", description: "Social media, branding, website & app design, creative production, digital consultation and performance marketing — delivered in-house." },
      work: { title: "Work", description: "Selected work for Texas Chicken, Shark Tank Egypt, Sinclair, Physiowell and more — brands, platforms and campaigns across MENA." },
      team: { title: "Team", description: "The people behind the work at PSdigital — leadership, discipline leads and the studio in Alexandria and Dubai." },
      careers: { title: "Careers", description: "Open roles at PSdigital. Apply in three steps and send us your work." },
      contact: { title: "Contact", description: "Contact PSdigital — send a question or report a problem, and find our offices in Alexandria and Dubai." },
      industries: { title: "Industries", description: "Restaurants, healthcare, media, real estate and lifestyle brands — the sectors we know, each backed by real case studies." },
      insights: { title: "Insights", description: "Practical notes from building and marketing brands and digital products across MENA." },
      start: { title: "Start a project", description: "Tell us about your project in one short form. A strategist and a creative lead reply within two working days." },
      notFound: { title: "Page not found", description: "This page does not exist." },
    },
  },

  nav: {
    /** Sitemap order. */
    primary: [
      { label: "About", href: "/about" },
      // { label: "Work", href: "/portfolio" }, // hidden for now
      { label: "Projects", href: "/portfolio" },
      { label: "Services", href: "/services" },
      { label: "Insights", href: "/insights" },
      { label: "Careers", href: "/careers" },
    ],
    contact: { label: "Contact us", href: "/contact" },
    start: { label: "Start a project", href: "/start" },
    team: { label: "Team", href: "/team" },
    menus: { flagship: "Flagship" },
  },

  ui: {
    skip: "Skip to content",
    home: "Home",
    homeLabel: "PSdigital — home",
    mainNav: "Main",
    menu: "Menu",
    close: "Close",
    language: "Language",
    switchTo: "العربية",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    scroll: "Scroll",
    view: "View",
    viewCase: "View case",
    all: "All",
    next: "Next",
    previous: "Previous",
    back: "Back",
    readMore: "Read more",
    localTime: "Local time",
    backToTop: "Back to top",
    directions: "Get directions",
    copyright: "All rights reserved.",
    loading: "Loading",
    required: "Required",
    optional: "Optional",
  },

  footer: {
    closing: ["Endless", "possibilities"],
    lead: "Have something in mind? We would like to hear it.",
    sitemap: "Sitemap",
    services: "Services",
    industries: "Industries",
    company: "Company",
    studios: "Studios",
    follow: "Follow us",
    careers: "Join the team",
    awards: "Awards & partnerships",
  },

  home: {
    hero: {
      eyebrow: "Creative & digital partner",
      title: ["Connected flow,", "endless possibilities"],
      intro: "Strategy, creativity and innovation, working as one. We build brands and digital products that drive growth, across MENA and beyond.",
      primary: "See the work",
      secondary: "What we do",
    },
    proof: {
      label: "Proof, not promises",
      title: ["Heard from", "our clients"],
      pending: "Quote to collect",
      clients: "Choose a result",
      previous: "Previous result",
      next: "Next result",
      pause: "Pause rotation",
      play: "Resume rotation",
      /**
       * Each quote carries the result behind it, drawn by `viz` (multiplier, reach or days). `mark` is the file in /public/images/clients/marks.
       * Quotes marked `pending` are placeholders: replace text, name and role with a real, approved quote
       * and drop the flag. Until then they render in a dashed "to collect" state.
       */
      items: [
        {
          value: "16×",
          caption: "return on ad spend",
          client: "ZEE",
          mark: "zee",
          viz: "multiplier",
          quote: { text: "Your client's words go here: one sentence on what changed after the campaign went live.", name: "Name Surname", role: "Title, ZEE", pending: true },
        },
        {
          value: "10M",
          caption: "people reached every month",
          client: "Pharco",
          mark: "pharco",
          viz: "reach",
          quote: { text: "A second client's words: the result they would tell a peer about, in their own voice.", name: "Name Surname", role: "Title, Pharco", pending: true },
        },
        {
          value: "50",
          caption: "days to design and build a site for 5 countries",
          client: "Burger King",
          mark: "burger-king",
          viz: "days",
          quote: { text: "A third client's words: what working with the team felt like, from brief to launch day.", name: "Name Surname", role: "Title, Burger King", pending: true },
        },
      ],
    },
    positioning: {
      label: "Who we are",
      statement:
        "PSdigital is your creative partner. We bring strategy, creativity and innovation together, to move brands, people, and business forward.",
      pillars: [
        { title: "Strategy", body: "Moves brands. Positioning that gives every decision a direction." },
        { title: "Creativity", body: "Moves people. Ideas and content they notice, feel and share." },
        { title: "Innovation", body: "Moves business. Digital products and performance built to grow." },
      ],
    },
    showreel: {
      label: "Showreel",
      year: "2026",
      play: "Play",
      reel: "Reel",
      slides: [
        { image: "/images/site/who-we-are-room.webp", alt: "The PSdigital team beside work for Sinclair and the Texas Chicken app" },
        { image: "/images/projects/texas-chicken/hero.webp", alt: "Texas Chicken campaign" },
        { image: "/images/projects/sinclair-aesthetics/hero.webp", alt: "Sinclair Aesthetics campaign" },
        { image: "/images/projects/shark-tank-egypt/hero.webp", alt: "Shark Tank Egypt" },
        { image: "/images/projects/physiowell/hero.webp", alt: "Physiowell campaign" },
      ],
    },
    work: {
      label: "Projects",
      title: ["Work that", "moves"],
      intro: "Creative work built for brands with more than one market in mind.",
      cta: "All work",
      /** The pinned orbit of flagship cases (home/universe). One item per featured slug, in featured order. */
      universe: {
        eyebrow: ["One studio", "Four worlds"],
        items: [
          {
            slug: "texas-chicken",
            prefix: "Brand · App · 16 markets",
            name: "Texas Chicken",
            kicker: "Order",
            line: "One bilingual brand and one regional ordering app — sixteen countries, one checkout, one agency of record.",
            cta: "Inside the app",
          },
          {
            slug: "shark-tank-egypt",
            prefix: "Social · Website",
            name: "Shark Tank",
            kicker: "Pitch",
            line: "Accounts built from zero, episodes dropped to the minute, and a bilingual home where founders apply to pitch.",
            cta: "Inside the show",
          },
          {
            slug: "elsewhere-developments",
            prefix: "Developments · Real estate",
            name: "Elsewhere",
            kicker: "Arrive",
            line: "One developer, three destinations — Ajaza and The One, each with its own voice inside a single visual system.",
            cta: "Inside the launch",
          },
          {
            slug: "physiowell",
            prefix: "Performance · Dubai",
            name: "Physiowell",
            kicker: "Scale",
            line: "Symptom-led hooks tested against real lead numbers, winners scaled across three channels — up to 10× ROAS.",
            cta: "Inside the numbers",
          },
        ],
        scenes: {
          texas: { featured: "Featured market", title: "One regional app", action: "Order now", menu: ["Bucket", "Tenders", "Wrap", "Sides"], markets: "Markets", coupon: "E-coupon −20%", checkout: "One checkout" },
          shark: { live: "Live", episode: "Season 4 · New episode", drop: "Dropped 21:00 sharp", views: "Viewers", pitches: "Pitches", season: "Season" },
          elsewhere: { places: ["Ajaza", "The One Residences", "The One Offices"], count: "Destinations", system: "One visual system", launch: "Launch campaign live" },
          physiowell: { hooks: ["Frozen shoulder", "Scoliosis", "Pregnancy"], scaled: "Scaled", retired: "Retired", roas: "ROAS", channels: ["Facebook", "Instagram", "Google"] },
        },
      },
    },
    services: {
      label: "Services",
      title: ["Serving", "what you need"],
      intro: "Everything you need to move your business forward.",
      cta: "All services",
    },
    industries: {
      label: "Industries",
      title: ["We know", "your sector"],
      intro: "Restaurants are where we are strongest. We also build and market for healthcare, media, real estate and lifestyle brands.",
      cta: "All industries",
    },
    clients: {
      label: "Clients",
      title: ["Brands", "we move"],
      intro: "From global names to fast-growing regional challengers.",
    },
    process: {
      label: "How we work",
      title: ["Our", "process"],
    },
    insights: {
      label: "Insights",
      title: ["Learned from", "the field"],
      intro: "What we see across markets, platforms and projects.",
      cta: "All insights",
    },
    closing: {
      label: "Next",
      title: ["Let's build your", "next move"],
      body: "Bring the brief, and we'll take it from there.",
      primary: "Start a project",
      secondary: "Join the team",
    },
  },

  services: {
    hero: {
      label: "Services",
      title: ["Every", "discipline"],
      intro:
        "Six disciplines delivered end to end by 80+ in-house specialists. Strategy shapes the identity, and the identity shapes the platform, the campaign and every post that runs on it.",
    },
    labels: { deliverables: "What you get", projects: "See projects using this service", explore: "Explore the service" },
    detail: {
      back: "All services",
      deliverables: { label: "What you get", title: ["What we", "deliver"] },
      work: { label: "Selected work", title: ["In", "practice"], all: "All {service} work" },
      industries: { label: "Industries", title: ["Where it", "works"], all: "All industries" },
      faq: { label: "Questions", title: ["Frequently", "asked"] },
      numbers: "In numbers",
      closing: {
        label: "Next",
        title: ["Start with", "one discipline"],
        body: "Most partners start with one discipline and grow into several. Tell us where you are starting.",
        primary: "Start a project",
        secondary: "All services",
      },
    },
    list: [
      {
        slug: "social-media",
        title: "Social Media",
        headline: ["Always", "on"],
        summary: "Daily content, real conversations, and a voice your audience recognises.",
        intro: "Strategy, content and community for brands that publish every day. One team plans the calendar, makes the posts and answers the comments, in Arabic and English.",
        faq: [
          { question: "Do you work in Arabic and English?", answer: "Yes. We plan, write and manage content in both, including mixed tones where the brand calls for it." },
          { question: "Can you start a brand's accounts from zero?", answer: "Yes. Shark Tank Egypt started with no social presence; we built the accounts and grew them season after season." },
          { question: "How do you report?", answer: "Monthly, against the goals we agreed at the start: reach where it matters, but also leads, applications or sales." },
        ],
        deliverables: [
          { title: "Channel strategy", body: "Which platforms matter for your audience, what each one is for, and the tone the brand speaks in on every one." },
          { title: "Content calendars", body: "Monthly plans built around launches, seasons and culture, approved ahead so publishing never runs on last-minute ideas." },
          { title: "Always-on creative", body: "Posts, reels, stories and carousels made every week by our own designers, writers and motion team." },
          { title: "Community management", body: "Comments and messages answered in the brand's voice, in Arabic and English, with clear routes for complaints and leads." },
          { title: "Influencer programmes", body: "Creators chosen for fit rather than follower count, then briefed, contracted and measured like any other channel." },
          { title: "Social listening & reporting", body: "What people say about you and your category, plus monthly reports against the goals we agreed at the start." },
        ],
        numbers: [
          { value: 900, suffix: "M+", label: "Viewership for a show whose accounts we built from zero" },
          { value: 170, suffix: "+", label: "Companies that applied online and pitched on Shark Tank Egypt" },
          { value: 4, suffix: "", label: "Seasons of always-on content, published with every episode" },
          { value: 2, suffix: "", label: "Languages on every post, Arabic and English" },
        ],
        proof: "shark-tank-egypt",
        image: "/images/services/social-media-v3.webp",
      },
      {
        slug: "branding",
        title: "Branding",
        headline: ["Built", "to last"],
        summary: "Positioning and identity that define who you are, everywhere.",
        intro: "Positioning, identity and bilingual brand systems built to travel. We design in Arabic and English from the first sketch, so the brand reads the same in every market.",
        faq: [
          { question: "Can one brand work across many markets?", answer: "Yes. Texas Chicken runs one bilingual brand system across sixteen markets in the Middle East and Africa." },
          { question: "Do you design in Arabic from the start?", answer: "Always. Arabic and English are designed together, never translated after the fact." },
          { question: "What do we get at the end?", answer: "Guidelines and toolkits your team and partners can use without us in the room." },
        ],
        deliverables: [
          { title: "Brand strategy & positioning", body: "Research, audience and competitors distilled into one clear idea of what the brand stands for and why it wins." },
          { title: "Naming & verbal identity", body: "Names checked across languages and markets, plus the tone of voice and key messages that make the brand sound like itself." },
          { title: "Visual identity systems", body: "Logo, colour, type, imagery and layout designed as one flexible system rather than a single mark." },
          { title: "Bilingual typography", body: "Arabic and English set side by side from the first sketch, paired, balanced and tested in real layouts." },
          { title: "Guidelines & toolkits", body: "Clear rules, templates and asset libraries your team and partners can use without us in the room." },
          { title: "Packaging & retail", body: "The brand brought onto shelves, stores and menus, from packaging structure to in-store signage." },
        ],
        numbers: [
          { value: 16, suffix: "", label: "Markets running on one bilingual brand system" },
          { value: 1, suffix: "", label: "Identity replacing sixteen country-by-country looks" },
          { value: 2, suffix: "", label: "Languages designed together from the first sketch" },
          { value: 3, suffix: "", label: "Sub-brands brought under one visual language" },
        ],
        proof: "texas-chicken",
        image: "/images/services/branding-v3.webp",
      },
      {
        slug: "website-app-design",
        title: "Website & App Design",
        headline: ["Designed", "& built"],
        summary: "Digital experiences built around how people think, click, browse and buy.",
        intro: "Websites, ordering apps, loyalty and kiosks: researched, designed and engineered under one roof, so what is designed is what ships.",
        faq: [
          { question: "Can one platform serve several countries?", answer: "Yes. The Texas Chicken ordering app replaced sixteen country-by-country experiences with one market-aware journey." },
          { question: "Do you build as well as design?", answer: "Yes. Research, UI and engineering sit in the same team, from the first flow to the release." },
          { question: "Do you support the product after launch?", answer: "Yes. We keep improving and supporting products once they are live." },
        ],
        deliverables: [
          { title: "UX research & flows", body: "Interviews, analytics and competitor reviews turned into journeys and wireframes before anything is drawn." },
          { title: "UI design systems", body: "Components, tokens and patterns that keep every screen consistent and let new features ship faster." },
          { title: "Websites & e-commerce", body: "Fast, bilingual sites and online stores, built to convert and easy for your team to update." },
          { title: "iOS & Android apps", body: "Apps designed and engineered in-house, from the first prototype to the store release." },
          { title: "Loyalty & ordering", body: "Ordering, payments, rewards and kiosks that bring customers back, built for one market or sixteen." },
          { title: "Headless & custom builds", body: "Custom platforms, integrations and headless setups for when an off-the-shelf template will not do the job." },
        ],
        numbers: [
          { value: 16, suffix: "", label: "Countries ordering through one regional app" },
          { value: 1, suffix: "", label: "Checkout, replacing sixteen separate journeys" },
          { value: 3, suffix: "", label: "Ways to order on one journey: delivery, pick-up and dine-in" },
          { value: 2, suffix: "", label: "Taps from craving to checkout in a dessert app" },
        ],
        proof: "million-pound-menu",
        image: "/images/services/website-app-design-v3.webp",
      },
      {
        slug: "creative-production",
        title: "Creative Production",
        headline: ["Made", "in-house"],
        summary: "Making every frame visible with creative production, from key visuals to always-on assets.",
        intro: "Photography, film, motion and 3D produced by our own studio. The key visual and the hundredth always-on post come from the same team.",
        faq: [
          { question: "Do you shoot in-house?", answer: "Yes. Art direction, photography, film and post-production are handled by our own studio." },
          { question: "Can you produce for social and out-of-home?", answer: "Yes. M Squared's “Beyond Time.” ran from billboards to street posters to the feed." },
          { question: "How fast can you turn content around?", answer: "For formats on air, the same week. Shark Tank Egypt's content goes live with each episode." },
        ],
        deliverables: [
          { title: "Art direction", body: "One visual direction for every shoot and asset, so the campaign looks the same on a billboard and in the feed." },
          { title: "Photography", body: "Product, food, people and lifestyle photography, shot by our own photographers and styled by our team." },
          { title: "Film & TVC", body: "Brand films, TV commercials and social video, from script and casting to the final cut." },
          { title: "Motion & 3D", body: "Animated logos, explainers, product renders and 3D scenes that take the brand beyond still images." },
          { title: "Post-production", body: "Editing, colour grading, retouching, sound and subtitles, finished in-house for every format and ratio." },
          { title: "Studio & location shoots", body: "Shoots planned and run end to end, in our studio or on location, with crew, permits and logistics handled." },
        ],
        numbers: [
          { value: 80, suffix: "+", label: "In-house specialists, so no shoot is subcontracted" },
          { value: 4, suffix: "", label: "Seasons of Shark Tank Egypt content, live with every episode" },
          { value: 3, suffix: "", label: "Executions carrying one line, from billboards to street posters" },
          { value: 2, suffix: "", label: "Languages every asset is produced in from the start" },
        ],
        proof: "m-squared",
        image: "/images/services/creative-production-v3.webp",
      },
      {
        slug: "digital-consultation",
        title: "Digital Consultation",
        headline: ["Think", "first"],
        summary: "Research, audits and roadmaps to point your next move.",
        intro: "Audits, roadmaps and a clear point of view before anything is designed or bought. We look at where you are, decide where to go, and plan the route.",
        faq: [
          { question: "What does a consultation produce?", answer: "A written audit, a prioritised roadmap and the budget it needs, ready for your team or ours." },
          { question: "Can you work with our in-house team?", answer: "Yes. Many engagements end with your team running the plan, with us on call." },
          { question: "Why not start with the campaign?", answer: "Gaps found in a plan cost far less to fix than gaps found after the spend." },
        ],
        deliverables: [
          { title: "Digital & brand audits", body: "An honest look at your channels, site, content and brand: what works, what does not, and why." },
          { title: "Audience & market research", body: "Who your customers are, how they decide and what competitors do, grounded in data and interviews." },
          { title: "Channel & platform roadmaps", body: "A prioritised plan for which channels and platforms to build, when, and with what budget." },
          { title: "Marketing technology", body: "The right CRM, analytics and automation tools, chosen, connected and set up to work together." },
          { title: "Team & process design", body: "Roles, workflows and approval routes that let your in-house team move faster with fewer handovers." },
          { title: "Workshops", body: "Focused sessions with your leadership and teams to agree on goals, priorities and the next step." },
        ],
        numbers: [
          { value: 6, suffix: "", label: "Disciplines a roadmap can call on, all in-house" },
          { value: 3, suffix: "", label: "Sub-brands brought under one regional strategy" },
          { value: 2, suffix: "", label: "Audiences, consumers and clinicians, served by one plan" },
          { value: 1, suffix: "", label: "Clinical education platform planned around a product portfolio" },
        ],
        proof: "sinclair-aesthetics",
        image: "/images/services/digital-consultation-v3.webp",
      },
      {
        slug: "performance-marketing",
        title: "Performance Marketing",
        headline: ["Measured,", "not guessed"],
        summary: "Paid media, smart targeting and constant optimisation for real results.",
        intro: "Paid media, SEO and continuous testing, measured against revenue rather than impressions. Every creative is a test, and the winners get the budget.",
        faq: [
          { question: "How do you measure success?", answer: "By the outcome you care about: leads, bookings, orders or return on ad spend. For Physiowell that meant up to 10x ROAS." },
          { question: "Which platforms do you run?", answer: "Meta, TikTok, Snapchat, X and Google, plus SEO and content for search." },
          { question: "How quickly will we see results?", answer: "Tests start returning signal within weeks; we scale what works and stop what does not." },
        ],
        deliverables: [
          { title: "Media planning & buying", body: "Budgets split across Meta, TikTok, Snapchat, X and Google by where your customers actually convert." },
          { title: "Performance creative", body: "Ads made to be tested: many hooks, formats and messages, with the winners getting the budget." },
          { title: "SEO & content", body: "Technical fixes, keyword strategy and bilingual content that earn traffic you do not pay for per click." },
          { title: "Tracking & attribution", body: "Pixels, events and dashboards set up properly, so every lead, booking and order is traced to its source." },
          { title: "A/B testing", body: "Structured tests on ads, landing pages and offers, run until the numbers say which version wins." },
          { title: "Reporting & optimisation", body: "Clear reports on the outcomes you care about, with budget moved every week toward what performs." },
        ],
        numbers: [
          { value: 10, suffix: "×", label: "Up to, return on ad spend for a Dubai clinic" },
          { value: 3, suffix: "", label: "Always-on channels measured against real lead numbers" },
          { value: 5, suffix: "", label: "Platforms we plan and buy on: Meta, TikTok, Snapchat, X and Google" },
          { value: 16, suffix: "", label: "Markets where search and social run on one brand system" },
        ],
        proof: "physiowell",
        image: "/images/services/performance-marketing-v3.webp",
      },
    ],
    process: { label: "How we work", title: ["From first idea", "to last pixel"] },
    closing: {
      label: "More than one discipline?",
      title: ["Let's build", "the whole system"],
      body: "Most of our partners start with one discipline and grow into several. Tell us where you are starting.",
      primary: "Start a project",
      secondary: "See the work",
    },
  },

  work: {
    hero: {
      label: "Work",
      title: ["Selected", "work"],
      intro: "Brand systems, platforms and campaigns for companies that run across markets. Filter by what you need.",
    },
    filterLabel: "Filter work by discipline",
    industryFilterLabel: "Filter work by industry",
    filters: { label: "Filter", service: "Service", industry: "Industry", clear: "Clear filters", results: "projects" },
    empty: "No work in this discipline yet.",
    clients: { label: "Clients", title: ["Trusted by"] },
    case: {
      client: "Client",
      market: "Market",
      industry: "Industry",
      services: "Disciplines",
      deliverables: "Deliverables",
      next: "Next case",
      back: "All work",
      overview: "Overview",
      challenge: "The challenge",
      approach: "What we did",
      results: "The result",
      review: "Client review",
      links: "See it live",
      linkNames: {
        website: "Website",
        app: "App",
        appStore: "App Store",
        googlePlay: "Google Play",
        instagram: "Instagram",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        tiktok: "TikTok",
        youtube: "YouTube",
        x: "X",
        behance: "Behance",
      },
    },
  },

  industries: {
    hero: {
      label: "Industries",
      title: ["Built for", "your sector"],
      intro: "Every industry below links to real work. Restaurants are our deepest specialism; the others are sectors where we have shipped and measured.",
    },
    labels: {
      projects: "{count} projects",
      back: "All industries",
      challenges: { label: "What we hear", title: ["The problems", "we solve"] },
      work: { label: "More work", title: ["More in", "this sector"], all: "All {industry} projects" },
      helps: { label: "How we help", title: ["What we", "bring"], service: "Service details", projects: "See projects" },
      more: { label: "More sectors", title: ["Other", "industries"], all: "All industries" },
      proof: "Across the sector",
      stages: { label: "Where you are", title: ["Wherever", "you start"], intro: "Every brand in this sector came to us at a different point. Find yours, and see the work that answered it." },
      stageCase: "See the case",
      stageStart: "Start here",
      lessons: { label: "What we learned", title: ["What the sector", "taught us"] },
      insights: { label: "Insights", title: ["Reading", "for this sector"] },
      faq: { label: "Questions", title: ["Frequently", "asked"] },
    },
    closing: {
      label: "Your sector",
      title: ["Tell us", "what you sell"],
      body: "Whatever the market, the first conversation is about your customers. Tell us who they are.",
      primary: "Start a project",
      secondary: "See the work",
    },
  },

  insights: {
    hero: {
      label: "Insights",
      title: ["What we", "have learned"],
      intro: "Practical notes from building and marketing brands and digital products in the region, written from the work.",
    },
    filterLabel: "Filter insights by topic",
    minutes: "{count} min read",
    toc: "In this article",
    related: "Read the case study",
    back: "All insights",
    more: { label: "Keep reading", title: ["More", "insights"] },
  },

  about: {
    hero: {
      label: "About",
      title: ["Creative", "partner"],
      intro:
        "We are a creative and digital partner for brands across MENA and beyond. Strategy, creativity and innovation work as one team in Alexandria and Dubai.",
    },
    statement: {
      label: "Our story",
      text: "We started with one belief of getting ideas moving faster, with fewer gaps and people working as one. Today, 80+ specialists across creativity, technology and performance bring that approach to every brief.",
    },
    numbers: {
      label: "In numbers",
      items: [
        { value: 80, suffix: "+", label: "In-house specialists" },
        { value: 6, suffix: "", label: "Disciplines, end to end" },
        { value: 16, suffix: "", label: "Markets on one brand system" },
        { value: 2023, suffix: "", label: "Digital Agency of the Year" },
      ],
    },
    awards: {
      label: "Awards & partnerships",
      title: ["Recognized", "for the work"],
      intro: "Independent juries and the platforms we build on have backed the same thing our clients do: strategy first, everything made in-house.",
    },
    principles: { label: "What we believe", title: ["Why brands", "stay"] },
    process: { label: "How we work", title: ["Our", "process"] },
    clients: { label: "Our clients", title: ["Brands", "that stay"], intro: "From P&G, Burger King, Toyota and Sinclair to fast-growing regional brands like Shark Tank Egypt and ASTK." },
    closing: {
      label: "Work with us",
      title: ["Let's build", "what's next"],
      body: "Bring us the brief, the launch or the problem. We will bring the whole team.",
      primary: "Start a project",
      secondary: "Join the team",
    },
  },

  team: {
    hero: {
      label: "Team",
      title: ["People", "behind", "the work"],
      intro: "Strategists, designers, engineers, writers and producers under one roof. The people who win the brief are the people who ship it.",
    },
    leadership: {
      label: "Leadership",
      quote:
        "We built PSdigital for what comes after launch. A brand is shaped by the decisions that follow, so we stay for them, and judge our work by what still works years later.",
      portraitAlt: "Portrait of the PSdigital Chief Executive Officer",
    },
    leads: {
      label: "Our team",
      title: ["The people", "who set the bar"],
      intro: "The leadership, directors and makers who review every piece of work before it leaves the studio.",
      more: { value: "80+", title: "specialists behind them", action: "Join us" },
    },
    disciplines: {
      label: "Crafts",
      title: ["Seven crafts,", "one room"],
      items: [
        { title: "Strategy", body: "Audience, positioning and the point of view behind every brief." },
        { title: "Design", body: "Identity, campaign and product design, bilingual from day one." },
        { title: "Motion", body: "2D, 3D and film that make brands move the way they sound." },
        { title: "Content", body: "Copy, social and production for brands that publish every day." },
        { title: "Development", body: "Websites, ordering platforms and kiosks, engineered in-house." },
        { title: "UI/UX", body: "Research, flows and design systems that scale across markets." },
        { title: "Performance", body: "Paid media and testing measured against real numbers." },
      ],
    },
    closing: {
      label: "Want a seat in the room?",
      title: ["Join", "the team"],
      body: "We hire people who want to see an idea through, from the first sketch to the numbers it moves.",
      primary: "Open roles",
      secondary: "About us",
    },
  },

  careers: {
    hero: {
      label: "Careers",
      title: ["Make", "what's next"],
      intro: "Join 80+ strategists, designers, engineers, writers and producers in Alexandria and Dubai. Apply in three steps and let your work speak first.",
      cta: "Apply now",
      browse: "See open roles",
    },
    values: {
      label: "Life at PSdigital",
      title: ["Good work,", "good rooms"],
      intro: "Four reasons people stay and do their best work here. Hover or tap each one to see what a week at PSdigital looks like.",
      perks: { label: "Perks", items: ["Hybrid and remote roles", "Learning budget", "Health insurance", "Paid time to recharge", "Alexandria and Dubai studios"] },
      items: [
        { title: "Craft over volume", body: "Fewer projects, done properly, with your name on the work. We give ideas the time and attention they need, from the first sketch to the final file.", image: "/images/careers/craft.webp" },
        { title: "Everyone in the room", body: "Strategy, design, tech and media sit at the same table from day one. Every discipline shares the brief, the timeline and the credit.", image: "/images/careers/room.webp" },
        { title: "Measured, not guessed", body: "Ideas are tested against real numbers, and you see the results of your own work. That is how we learn and how we get better.", image: "/images/careers/measured.webp" },
        { title: "Growth is the job", body: "Mentorship, honest reviews, a learning budget and time to learn are part of the week, not an extra on top of it.", image: "/images/careers/growth.webp" },
      ],
    },
    role: {
      back: "All roles",
      view: "View role",
      apply: { label: "Apply", title: ["Apply for", "this role"] },
      about: "About the role",
      responsibilities: "Responsibilities",
      requirements: "Requirements",
      overview: "Role overview",
      team: "Team",
      location: "Location",
      type: "Type",
      reply: "We reply to everyone, usually within ten working days.",
      more: { label: "More roles", title: ["Other", "open roles"] },
      open: {
        id: "open-application",
        title: "Open application",
        department: "Any team",
        location: "Alexandria or Dubai",
        type: "Full-time",
        summary: "Don't see your role? Tell us what you do best and where you would fit. We read every application, and if there is a fit now or later, we will be in touch.",
        cta: "Send an open application",
        prompt: "Don't see your role?",
      },
    },
    roles: {
      label: "Open roles",
      title: ["Where you", "could fit"],
      filterLabel: "Filter roles by team",
      allTeams: "All teams",
      search: { label: "Search roles", placeholder: "Search by title, team or skill" },
      filters: {
        toggle: "Filters",
        search: "Search",
        department: "Department",
        allDepartments: "All departments",
        location: "Location",
        allLocations: "All locations",
        type: "Type",
        allTypes: "All types",
      },
      showing: "Showing {shown} of {total} open roles",
      clear: "Clear filters",
      noMatch: "No roles match your search.",
      youWill: "You will",
      youBring: "You bring",
      apply: "Apply for this role",
      empty: "No roles in this team right now. Send an open application below.",
    },
    apply: {
      label: "Apply",
      title: ["Three", "steps"],
      intro: "No cover letter needed. Tell us who you are, show us your work, and send it.",
      steps: ["You", "Your work", "Send"],
      fields: {
        name: { label: "Full name", placeholder: "Your name" },
        email: { label: "Email", placeholder: "you@email.com" },
        phone: { label: "Phone", placeholder: "100 123 4567", country: "Country code", search: "Search country or code", empty: "No matching country" },
        role: { label: "Role", placeholder: "Choose a role" },
        openApplication: "Open application",
        portfolio: { label: "Portfolio or CV link", placeholder: "https://" },
        file: { label: "Or upload a PDF", hint: "PDF, up to 8 MB", choose: "Choose file", replace: "Replace" },
        note: { label: "A few lines about you", placeholder: "The work you are proudest of, and why" },
        consent: "I agree that PSdigital may keep my application for 12 months to contact me about roles.",
      },
      review: "Review",
      continue: "Continue",
      back: "Back",
      submit: "Send application",
      sending: "Sending…",
      success: {
        title: "Application received.",
        body: "Thank you. The lead of your discipline reviews every application and we reply to everyone, usually within ten working days.",
        again: "Send another",
      },
      fallback: {
        title: "One last step",
        body: "Online applications are not connected yet. Your email app will open with everything filled in. Attach your PDF there.",
        action: "Open email",
      },
      errors: {
        name: "Please tell us your name.",
        email: "Please enter a valid email address.",
        work: "Add a portfolio link or upload a PDF.",
        url: "Please enter a full link, starting with https://",
        file: "Please upload a PDF up to 8 MB.",
        consent: "Please confirm so we can keep your application.",
        server: "Something went wrong on our side. Please try again, or write to us directly.",
      },
      email: { subject: "Application — {role}", role: "Role", name: "Name", email: "Email", phone: "Phone", portfolio: "Portfolio", note: "About me" },
    },
    process: {
      label: "How we hire",
      title: ["Four steps,", "no surprises"],
      steps: [
        { title: "Apply", body: "Send your work and a few lines. We reply to everyone." },
        { title: "Meet", body: "A conversation with the lead of your discipline." },
        { title: "Work together", body: "A short, paid exercise on a real brief." },
        { title: "Offer", body: "A clear offer, usually within two weeks." },
      ],
    },
  },

  contact: {
    hero: {
      label: "Contact",
      title: ["Get in", "touch"],
      intro: "A question, a problem with something we built, or anything that needs our attention — send it here and the right person will reply within one working day.",
    },
    form: {
      label: "Send us a message",
      fields: {
        name: { label: "Your name", placeholder: "Full name" },
        email: { label: "Email", placeholder: "you@company.com" },
        phone: { label: "Phone", placeholder: "100 123 4567", country: "Country code", search: "Search country or code", empty: "No matching country" },
        message: { label: "Message", placeholder: "Tell us what's happening — what you expected, what you saw, and any links or screens involved." },
      },
      submit: "Send message",
      sending: "Sending…",
      privacy: "We only use your details to reply to this message.",
      success: { title: "Thank you — it's with us.", body: "We've received your message and will reply within one working day." },
      fallback: {
        title: "One last step",
        body: "Online messages are not connected yet. Your email app will open with everything filled in.",
        action: "Open email",
      },
      errors: {
        name: "Please tell us your name.",
        email: "Please enter a valid email address.",
        phone: "Please enter a valid phone number, or leave it empty.",
        message: "Tell us a little more, at least 10 characters.",
        server: "Something went wrong on our side. Please try again, or write to us directly.",
      },
      email: { subject: "Contact — {name}", name: "Name", email: "Email", phone: "Phone", message: "Message" },
    },
    reach: { label: "Reach us", email: "Email" },
    offices: { label: "Our offices" },
    follow: { label: "Follow us" },
    project: { body: "Planning a new project?", action: "Send a project brief" },
  },

  start: {
    hero: {
      label: "Start a project",
      title: ["Tell us", "about it"],
      intro: "One short form, about two minutes. The more we know up front, the more useful our first conversation will be.",
    },
    label: "Project brief",
    process: "Our process",
    details: {
      title: "Your details",
      name: { label: "Full name", placeholder: "Your name" },
      company: { label: "Company", placeholder: "Brand or organisation" },
      email: { label: "Work email", placeholder: "you@company.com" },
      phone: { label: "Phone", placeholder: "100 123 4567", country: "Country code", search: "Search country or code", empty: "No matching country" },
      role: { label: "Your role", placeholder: "e.g. Marketing director" },
    },
    needs: {
      title: "What do you need?",
      unsure: "Not sure yet",
      services: { label: "Services", placeholder: "Choose services" },
      industry: { label: "Industry", placeholder: "Choose industries", other: "Other" },
      description: {
        label: "Describe the project",
        placeholder: "For example: an ordering app for our restaurants in Egypt and the UAE, with loyalty and a kiosk in our biggest branches.",
        hint: "At least 20 characters.",
      },
    },
    submit: "Send brief",
    sending: "Sending…",
    privacy: "We only use your details to reply to this brief.",
    errors: {
      needs: "Choose at least one service, or “Not sure yet”.",
      description: "Add a few more words about the project (at least 20 characters).",
      name: "Please tell us your name.",
      email: "Please enter a valid email address.",
      server: "Something went wrong on our side. Please try again, or write to us directly.",
    },
    success: { title: "Thank you — your brief is with us.", body: "A strategist and a creative lead will reply within two working days." },
    fallback: { title: "One last step", body: "Online briefs are not connected yet. Your email app will open with every answer filled in.", action: "Open email" },
    email: {
      subject: "Project brief — {company}",
      name: "Name",
      company: "Company",
      email: "Email",
      phone: "Phone",
      role: "Role",
      needs: "Needs",
      industry: "Industry",
      description: "The project",
    },
  },

  notFound: {
    label: "404",
    title: ["Lost in", "the glass"],
    body: "The page you are looking for has moved or never existed.",
    action: "Back home",
  },
} as const;

export type SiteCopyEn = typeof en;
