/**
 * Turns the client logos (public/images/clients/*.png, artwork on opaque white) into
 * white marks with real transparency, for ClientLogoSection.
 *
 * The shape is untouched: every pixel becomes white, and its alpha is how dark the
 * artwork is there (inverted luminance, contrast lifted so paper-white drops out fully,
 * then levelled so each logo's darkest tone is solid). On a dark page that is the same
 * picture as the old inverted + screen-blended logo, but with an alpha channel, so the
 * marks can move, blur, glow and mask a shimmer without a box around them.
 *
 * Run: node scripts/client-marks.mjs
 * Writes public/images/clients/marks/*.webp and src/data/client-marks.ts (their sizes).
 */
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SOURCE = path.resolve("public/images/clients");
const OUT = path.join(SOURCE, "marks");
const MANIFEST = path.resolve("src/data/client-marks.ts");
const CONTRAST = 1.35;

await mkdir(OUT, { recursive: true });
const files = (await readdir(SOURCE)).filter((file) => file.endsWith(".png")).sort();
const sizes = [];

for (const file of files) {
  const { data, info } = await sharp(path.join(SOURCE, file)).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const count = info.width * info.height;
  const ink = new Float32Array(count);
  let peak = 0;
  for (let i = 0; i < count; i++) {
    const luminance = (0.2126 * data[i * 3] + 0.7152 * data[i * 3 + 1] + 0.0722 * data[i * 3 + 2]) / 255;
    ink[i] = Math.min(1, Math.max(0, (0.5 - luminance) * CONTRAST + 0.5));
    if (ink[i] > peak) peak = ink[i];
  }

  const rgba = Buffer.alloc(count * 4, 255);
  for (let i = 0; i < count; i++) rgba[i * 4 + 3] = Math.round((ink[i] / peak) * 255);

  const name = file.replace(/\.png$/, "");
  const mark = await sharp(rgba, { raw: { width: info.width, height: info.height, channels: 4 } })
    .trim({ threshold: 8 })
    .webp({ lossless: true })
    .toFile(path.join(OUT, `${name}.webp`));
  sizes.push([name, mark.width, mark.height]);
  console.log(`${name}: ${mark.width}×${mark.height}`);
}

const manifest = `/** Generated by scripts/client-marks.mjs: pixel size of each mark in /public/images/clients/marks. */
export const clientMarks: Record<string, { width: number; height: number }> = {
${sizes.map(([name, width, height]) => `  ${JSON.stringify(name)}: { width: ${width}, height: ${height} },`).join("\n")}
};
`;
await writeFile(MANIFEST, manifest);
console.log(`\n${sizes.length} marks → ${path.relative(process.cwd(), OUT)}, sizes → ${path.relative(process.cwd(), MANIFEST)}`);
